// <auto-generated />
using ApiForBaseWeaknesses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiForBaseWeaknesses.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250701111017_InitialCreatee")]
    partial class InitialCreatee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiForBaseWeaknesses.Models.CvssMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseScore")
                        .HasColumnType("double precision")
                        .HasColumnName("Base_Score");

                    b.Property<string>("VectorString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Vector_String");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("VulnerabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("Vulnerability_Id");

                    b.HasKey("Id");

                    b.HasIndex("VulnerabilityId");

                    b.ToTable("CvssMetrics");
                });

            modelBuilder.Entity("ApiForBaseWeaknesses.Models.References", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VulnerabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("Vulnerability_Id");

                    b.HasKey("Id");

                    b.HasIndex("VulnerabilityId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("ApiForBaseWeaknesses.Models.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Published")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vulnerability");
                });

            modelBuilder.Entity("ApiForBaseWeaknesses.Models.CvssMetric", b =>
                {
                    b.HasOne("ApiForBaseWeaknesses.Models.Vulnerability", "Vulnerability")
                        .WithMany("CvssMetric")
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("ApiForBaseWeaknesses.Models.References", b =>
                {
                    b.HasOne("ApiForBaseWeaknesses.Models.Vulnerability", "Vulnerability")
                        .WithMany("Reference")
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("ApiForBaseWeaknesses.Models.Vulnerability", b =>
                {
                    b.Navigation("CvssMetric");

                    b.Navigation("Reference");
                });
#pragma warning restore 612, 618
        }
    }
}
